### ISSUE TITLE
Class 'obray\HTTP' not found

### ISSUE THREAD

**Issue by momocode-de** [nateobray/IPP#1]
Hi!

I just tested your IPP tool, but I got the following error:

`PHP Fatal error:  Uncaught Error: Class 'obray\HTTP' not found in /.../vendor/obray/ipp/src/Printer.php:351`

Why is this class missing?

**Comment by nateobray** [comment]
This is a good point.  I will remove the requirement for this library and just use a php curl request instead.  Update forthcoming.

**Comment by nateobray** [comment]
ok, the requirement for `obray/http` has been removed.  You should not get this error any longer.
