### ISSUE TITLE
Possible to ignore self-sign SSL Cert?

### ISSUE THREAD

**Issue by polppol** [nateobray/IPP#11]
Hi, when using secure URL with  self signed certificate
Uncaught Exception: SSL certificate problem: self signed certificate in Request.php:50 Stack 
will occure

Is it possible ignore / skip SSL check like this?
`curl_setopt($ch, CURLOPT_SSL_VERIFYPEER, false);`

**Comment by nateobray** [comment]
Sure, I've added the ability to pass in CURL options to `Request->send`.  You can do so like so:

```

$curlOptions = [
    ['key' => CURLOPT_SSL_VERIFYPEER, 'value' => false]
];

\obray\IPP\Request::send(
    $printerURI, 
    $encodedPayload, 
    $user, 
    $password, 
    $curlOptions
);
```
or more typical use case:
```
$printer = new \obray\IPP\Printer(
  {printer-uri},
  {username}, // optional
  {password},  // optional
  $curlOptions // optional
);
$response = $printer->printJob({raw document}, {attributes});
```

I have not tested this, so if you want to do me a favor and give it a go I'd be grateful.  Otherwise I'll setup a test when I can find some time.

**Comment by polppol** [comment]
Hi,
There was an issue in `Request.php` Line 46
`if(empty($curlOption['key']) || empty($curlOption['value'])) continue;`
should change to
`if(!isset($curlOption['key']) || !isset($curlOption['value'])) continue;`

as `empty($curlOption['value'])` will return `true` if `$curlOption['value']` is `false`

PR https://github.com/nateobray/IPP/pull/12

After change it setting curlOptions to ignore SSL cert is working fine
```
$ipp_url = "https://192.168.1.91:631/ipp/print";
$curlOptions = [
	['key' => CURLOPT_SSL_VERIFYPEER, 'value' => false],
	['key' => CURLOPT_SSL_VERIFYHOST, 'value' => false]
];

try{
	$ipp_printer = new obray\IPP\Printer(
		$ipp_url,
		'',
		'',
		$curlOptions
	);
}
catch (Exception $e) {
	die("Printer not response ". $e->__toString());
}

//getPrinterAttributes
$attributes = $ipp_printer->getPrinterAttributes();
```

**Comment by polppol** [comment]
PR https://github.com/nateobray/IPP/pull/12

**Comment by nateobray** [comment]
Perfect, thank you for the quick help.
