### ISSUE TITLE
Failed to connect to .... port 631: Connection refused

### ISSUE THREAD

**Issue by akostovGit** [nateobray/IPP#8]
Hi,

Great work, congratulations!

I noticed an issue with the IPP connection if the port is different than standard 631.  When trying with a different port we have an error: "Failed to connect to 127.0.0.1 port 631: Connection refused".

The issue is in the Request class. A static value for the port is set in the send function.
[https://github.com/nateobray/IPP/blob/aec639677d4b8af5a5505d00569fdad6046a097e/src/Request.php#L25](url)

**Comment by nateobray** [comment]
k, I can fix this in the next day or two.  Sorry for slow response, been out sick and then the holidays.

Follow up soon.

**Comment by janfejtek** [comment]
Hi, I created PR #10. I do not know that much about IPP, so I hope it makes sense

**Comment by nateobray** [comment]
Accepted pull request.  Thank you!

Closing.
